<div class="container">
    <form method="post">
        <div class="form-group">
            <label for="exampleInputEmail1">Playlist Name</label>
            <input type="text" class="form-control" name="name" id="exampleInputEmail1" aria-describedby="emailHelp">
        </div>
        <div class="form-group">
            <label for="exampleInputPassword1">Playlist Description</label>
            <input type="text" class="form-control" id="exampleInputPassword1" name="description">
        </div>
        <div class="form-group form-check">
            <select name="public" id="check">
                <option value="true">True</option>
                <option value="false">False</option>
            </select>
            <label class="form-check-label" for="public">Select visibility</label>

        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
</div>