<div class="container">
 
<h3>My Playlists</h3>
<?php
    echo $this->tag->linkTo(
        [
            "playlist/addNew",
            "Create New Playlist",
            'class' => 'btn btn-warning'
        ]
    );

    ?>
<div class="row">
<?php
    foreach($playlists as $list){
        echo '<div class="card mb-3">
        <img src="'.$list['image'].'" class="card-img-top" alt="...">
        <div class="card-body">
          <h5 class="card-title">'.$list['name'].'</h5>
          <p class="card-text">'.$list['description'].'.</p>
          <p class="card-text"><small class="text-muted">Owner :'.$list['owner'].'</small></p>
          <div class="card-footer bg-primary border-warning text-center">
          <form method="post" action="http://localhost:8080/playlist/list/'.$list['id'].'">
        <input type="submit" class="btn btn-warning btn-sm" value="More info"></form>
     </div>
        </div>
      </div>';
    }
    ?>
 
</div>
 
</div>