<div class="filter">
    <button class="btn btn-default" type="button" data-toggle="collapse" data-target="#mobile-filter" aria-expanded="true" aria-controls="mobile-filter">Filters
        <span class="fa fa-filter pl-1"></span></button>
</div>
</div>
<!-- Sidebar filter section -->
<section id="sidebar">
    <p> Home</p>
    <div class="border-bottom pb-2 ml-2">
        <h4 id="burgundy">Filters</h4>
    </div>
    <div class="py-2 border-bottom ml-3">
        <h6 class="font-weight-bold">Categories</h6>
        <div id="orange"><span class="fa fa-minus"></span></div>
        <form method="post">
            <input type="submit" class="btn btn-primary">
            <div class="form-group">
                <input type="text" name="search" class="bg-light" placeholder="Search tracks,albums,artist">
            </div>

            <div class="form-group">
                <input type="checkbox" name="check_list[]" value="album" id="artisan">
                <label for="artisan">Album</label>
            </div>
            <div class="form-group">
                <input type="checkbox" name="check_list[]" value="playlist" id="breakfast">
                <label for="breakfast">Playlists</label>
            </div>
            <div class="form-group">
                <input type="checkbox" name="check_list[]" value="artist" id="healthy">
                <label for="healthy">Artist</label>
            </div>
            <div class="form-group">
                <input type="checkbox" name="check_list[]" value="track" id="artisan">
                <label for="artisan">Track</label>
            </div>
            <div class="form-group">
                <input type="checkbox" name="check_list[]" value="show" id="breakfast">
                <label for="breakfast">Show</label>
            </div>
            <div class="form-group">
                <input type="checkbox" name="check_list[]" value="episode" id="healthy">
                <label for="healthy">Episode</label>
            </div>
        </form>
    </div>

</section>
<!-- products section -->
<section id="products">
    <div class="container">
        <div class="row">
        <?php
        if (isset($album)) {
            foreach ($album as $items) {
                foreach ($items as $title=>$value) {
                    echo "<div class='row'><h1>".$title."</h1></div><br>";
                    foreach ($value as $item) {
                        $details ='';
                        foreach ($item['others'][0] as $k=>$v) {
                            if ($k=='uri') {
                                $details .= '<audio controls>
                                    <source src="'.$v.'" type="audio/mpeg">
                                Your browser does not support the audio element.
                              </audio><form method="post" action="http://localhost:8080/playlist/addToPlaylist/'.$v.'"><label for="playlist">Add to Playlist</label><select name="playlist" id="playlist">';
                                foreach ($playlists as $list) {
                                    $details .= '<option value="'.$list['id'].'">'.$list['name'].'</option>';
                                }
                                $details .= '<input type="submit" class="btn btn-warning"></select></form>';
                            } else {
                                $details .= '<div class="text-muted">'.$k.' : ' . $v . '</div>';
                            }
                        }
                        $img = is_array($item['image'])?$item['image']['url']:$item['image'];
                        echo '<div class="card shadow m-2" style="width: 22rem;">
                        <img src="' .$img . '" class="card-img-top" alt="...">
                        <div class="card-body">
                          <h5 class="card-title">' . $item['name'] . '</h5>
                          <p class="card-text">'.$details.'.</p>
                        </div>
                      </div>';
                    }
                }
            }
        }
            ?>
        </div>
    </div>
</section>