<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <title>Spotify</title>

    <!-- jquery cdn -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <!-- Bootstrap core CSS -->
    <!-- Bootstrap core CSS -->
    <link href="../node_modules/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@5.15.4/css/fontawesome.min.css" integrity="sha384-jLKHWM3JRmfMU0A5x5AkjWkw/EYfGUAGagvnfryNV3F9VqM98XiIH7VBGVoxVSc7" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <style>
        .c {
            height: 400px;
        }

        .table-img {
            height: 25px;
        }

        .bd-placeholder-img {

            font-size: 1.125rem;
            text-anchor: middle;
            -webkit-user-select: none;
            -moz-user-select: none;
            user-select: none;
        }

        @media (min-width: 768px) {
            .bd-placeholder-img-lg {
                font-size: 3.5rem;
            }
        }

        body {
            margin: 0;
            font-family: "Lato", sans-serif;
        }

        .sidebar {
            margin: 0;
            padding: 0;
            width: 200px;
            background-color: #f1f1f1;
            position: fixed;
            height: 100%;
            overflow: auto;
        }

        .sidebar a {
            display: block;
            color: black;
            padding: 16px;
            text-decoration: none;
        }

        .sidebar a.active {
            background-color: #04AA6D;
            color: white;
        }

        .sidebar a:hover:not(.active) {
            background-color: #555;
            color: white;
        }

        div.content {
            margin-left: 200px;
            padding: 1px 16px;
            height: 1000px;
        }

        @media screen and (max-width: 700px) {
            .sidebar {
                width: 100%;
                height: auto;
                position: relative;
            }

            .sidebar a {
                float: left;
            }

            div.content {
                margin-left: 0;
            }
        }

        @media screen and (max-width: 400px) {
            .sidebar a {
                text-align: center;
                float: none;
            }
        }
    </style>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
</head>

<body>
    <header class="">
        <!-- navbar start -->
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container-fluid">
                <a class="navbar-brand ml-2 font-weight-bold" href="#">
                    <span id="burgundy">The</span>
                    <span id="orange">Music</span>
                </a>
                <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target="#navbarCollapse">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarCollapse">
                    <div class="navbar-nav">
                        <a href="/index" class="nav-item nav-link active">Home</a>
                        <?php echo $this->tag->linkTo(['playlist/index', 'My Playlists', 'class' => 'nav-item nav-link']); ?>
                    </div>
                    <div class="navbar-nav ms-auto">
                        <?php
                        echo isset($this->session->user) ? $this->tag->linkTo(['user/logout', 'Logout', 'class' => 'nav-item nav-link']) :
                            $this->tag->linkTo(['user/login', 'Login', 'class' => 'nav-item nav-link']);
                        ?>

                    </div>
                </div>
            </div>
        </nav>
        <!-- navbar end -->
    </header>
    <div class="sidebar">
    <form method="post">
            <input type="submit" class="btn btn-primary">
            <div class="form-group">
                <input type="text" name="search" class="bg-light" placeholder="Search tracks,albums,artist">
            </div>

            <div class="form-group">
                <input type="checkbox" name="check_list[]" value="album" id="artisan">
                <label for="artisan">Album</label>
            </div>
            <div class="form-group">
                <input type="checkbox" name="check_list[]" value="playlist" id="breakfast">
                <label for="breakfast">Playlists</label>
            </div>
            <div class="form-group">
                <input type="checkbox" name="check_list[]" value="artist" id="healthy">
                <label for="healthy">Artist</label>
            </div>
            <div class="form-group">
                <input type="checkbox" name="check_list[]" value="track" id="artisan">
                <label for="artisan">Track</label>
            </div>
            <div class="form-group">
                <input type="checkbox" name="check_list[]" value="show" id="breakfast">
                <label for="breakfast">Show</label>
            </div>
            <div class="form-group">
                <input type="checkbox" name="check_list[]" value="episode" id="healthy">
                <label for="healthy">Episode</label>
            </div>
        </form>
    </div>
    <div class="content container-fluid">
        <?php echo $this->getContent();
        echo PHP_EOL;
        ?>
    </div>
    <!-- Latest compiled and minified JavaScript -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="assets/script.js"></script>
</body>

</html>
<?php
